export const SET_INPUTS = 'SET_INPUTS';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

export const FETCH_REPOSITORIES_START = 'FETCH_REPOSITORIES_START';
export const FETCH_REPOSITORIES_SUCCESS = 'FETCH_REPOSITORIES_SUCCESS';
export const FETCH_REPOSITORIES_FAIL = 'FETCH_REPOSITORIES_FAIL';

export const FETCH_ISSUES_START = 'FETCH_ISSUES_START';
export const FETCH_ISSUES_SUCCESS = 'FETCH_ISSUES_SUCCESS';
export const FETCH_ISSUES_FAIL = 'FETCH_ISSUES_FAIL';